- name: "Checkout spdk"
  ansible.builtin.git:
    repo: 'https://github.com/spdk/spdk.git'
    dest: "{{ project_sources_dir }}/spdk"
    recursive: yes
    version: v22.09 # Sep 30, 2022
    depth: 1
    update: no

- name: "Checkout libvfio-user"
  ansible.builtin.git:
    repo: 'https://github.com/nutanix/libvfio-user.git'
    dest: "{{ project_sources_dir }}/libvfio-user"
    recursive: yes
    version: 388db3c4801b00f49befa3a2d0fb497fa90d58ce # Oct 5, 2022
    depth: 1
    update: no

- name: "Checkout oracle-qemu"
  ansible.builtin.git:
    repo: 'https://github.com/oracle/qemu.git'
    dest: "{{ project_sources_dir }}/qemu-orcl"
    recursive: yes
    version: 46bb039c31e92ae84cf7fe1f64119c1a78e0d101 # Jun 3, 2022
    depth: 1
    update: no

#- name: "Configure spdk with fio plugin"
#  register: spdk_reconfigured
#  ansible.builtin.command:
#    cmd: ./configure --with-fio={{ fio_source_dir }}
#    creates: "{{ spdk_source_dir }}/test/common/build_config.sh"
#    chdir: "{{ spdk_source_dir }}"

#- name: "Make spdk"
#  when: spdk_reconfigured.changed
#  ansible.builtin.command:
#    cmd: make
#    chdir: "{{ spdk_source_dir }}"
