- name: "Ensure 'at' is installed so we can disable exclusive access after a while"
  ansible.builtin.apt:
    name: at
    state: present

- name: "Ensure the ssh folder exists and it is writeable"
  ansible.builtin.file:
    path: /etc/ssh/sshd_config.d
    state: directory
    mode: '0744'

- name: "Configure exclusive SSH access"
  register: sshd_config_change
  ansible.builtin.template:
    src: templates/allow_access_user.conf.j2
    dest: /etc/ssh/sshd_config.d/allow_access_user.conf
    mode: '0644'

- name: "Trigger give access back to everyone in 4 hours"
  ansible.posix.at:
    command: rm -rf /etc/ssh/sshd_config.d/allow_access_user.conf && systemctl restart sshd
    count: 4
    units: hours
    unique: yes

- name: Restart ssh daemon
  when: sshd_config_change.changed
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: "Log out everyone except the current user"
  ignore_errors: true # In case there is no process
  ansible.builtin.shell:
    cmd: "loginctl --no-legend list-users | grep -v {{ remote_user }} | cut -d' ' -f1 | xargs -I{} killall --user {} --wait"

- name: Turn off nonessential services
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
  with_items:
    - containerd
    - docker
    - influxdb
