- name: Assert all code dependencies
  import_tasks: dependencies.yaml

- name: Make server have reproducible setup
  import_tasks: reproducible_setup.yaml

#- name: Obtain exclusive ssh access
#  import_tasks: exclusive_ssh_access.yaml
